language: node_js
node_js: lts/*
branches:
  only:
  - master
cache: npm
before_script:
- export TZ='Asia/Shanghai'
- npm install -g hexo-cli
install:
- cd blog
- npm install
script:
- hexo clean
- hexo generate
deploy:
  provider: pages
  strategy: git
  edge: true
  local_dir: public
  repo: rime/rime.github.io
  target_branch: master
  keep_history: false
  fqdn: rime.im
  cleanup: false
  token: $GITHUB_TOKEN
  on:
    branch: master
